export const PORTFOLIO_CONTENT = [
  {
    id: "vans",
    name: "Vans",
    featured: true,
    description: "Modern e-commerce experience showcasing Vans' iconic skateboarding culture",
    img: "/projects/vans/vans.png",
    url: "#",
    longDescription:
      "A motion-based concept inspired by Vans' brand identity. The project aimed to convey a youthful visual expression, drawing inspiration from street culture, graffiti, and skateboarding. Created in Adobe After Effects, with minor elements from Adobe Photoshop.",
    gallery: ["/projects/vans/vans.png"],
    videos: ["/projects/vans/vans-video.mp4"],
  },
  {
    id: "oatly-matcha",
    name: "Oatly - Matcha Campaign",
    featured: true,
    description: "Playful campaign design for Oatly's matcha product line",
    img: "/projects/oatly/oatly-matcha-banner.png",
    url: "#",
    longDescription:
      "A campaign project for Oatly where I explored the brand's playful and slightly cheeky tone of voice, interpreted in my own way. Focusing on their matcha product line with vibrant green aesthetics.",
    gallery: [
      "/projects/oatly/oatly-matcha-poster.png",
      "/projects/oatly/oatly-matcha-insta.png",
      "/projects/oatly/oatly-matcha-banner.png",
      "/projects/oatly/oatly-matcha-bus-mockup.png",
      "/projects/oatly/oatly-matcha-banner-mockup.png",
    ],
    videos: null,
  },
  {
    id: "oatly-xmas",
    name: "Oatly - Christmas Campaign",
    featured: true,
    description: "Festive and humorous holiday campaign for Oatly's seasonal products",
    img: "/projects/oatly/oatly-xmas-poster.png",
    url: "#",
    longDescription:
      "A sophisticated campaign for Oatly's Barista Edition, targeting coffee professionals and enthusiasts. The design language balanced premium appeal with Oatly's characteristic irreverence.",
    gallery: ["/projects/oatly/oatly-xmas-poster.png", "/projects/oatly/oatly-xmas-poster-mockup.png"],
    videos: null,
  },
  {
    id: "oatly-trimpath",
    name: "Oatly - Original",
    featured: false,
    description: "Clean and modern design for Oatly's original oat milk product packaging",
    img: "/projects/oatly/oatly-trimpath-thumb.png",
    url: "#",
    longDescription:
      "A minimalist design project for Oatly's original oat milk product. The focus was on creating a clean and modern aesthetic that reflects the brand's Swedish design heritage while maintaining its playful tone.",
    gallery: null,
    videos: ["/projects/oatly/oatly-trimpath.mp4"],
  },
  {
    id: "oatly-vanilla",
    name: "Oatly - Vanilla Sauce",
    featured: false,
    description: "Creative packaging and promotional design for Oatly's vanilla sauce product",
    img: "/projects/oatly/oatly-vanilla-sauce.png",
    url: "#",
    longDescription:
      "A separate campaign focusing on Oatly's vanilla sauce product range. This project emphasized the brand's minimalist Swedish design heritage while maintaining their signature playful tone.",
    gallery: null,
    videos: ["/projects/oatly/oatly-vanilla-sauce.mp4"],
  },
  {
    id: "bubs",
    name: "Bubs",
    featured: true,
    description: "Playful and vibrant design system for a modern confectionery brand",
    img: "/projects/bubs/bubs.png",
    url: "#",
    longDescription:
      "A playful and festive animation project inspired by BUBS’ colorful visual language. The project focuses on various animation techniques to create an energetic expression tailored for digital communication. Created in Adobe After Effects, combined with Adobe Photoshop.",
    gallery: null,
    videos: ["/projects/bubs/bubs-video.mp4"],
  },
  {
    id: "lyko",
    name: "Lyko",
    featured: false,
    description: "Beauty and cosmetics platform with elegant product showcases",
    img: "/projects/lyko/lyko-mockup-snow.png",
    url: "#",
    longDescription:
      "A Christmas-themed visual concept for Lyko, built using cut-out image compositions. I drew inspiration from Lyko’s established marketing style and adapted it to my own visual expression. Created in Adobe Photoshop, with a strong focus on layer management and structure.",
    gallery: ["/projects/lyko/lyko-poster.png", "/projects/lyko/lyko-mockup-snow.png"],
    videos: null,
  },
  {
    id: "indie-island",
    name: "Indie Island",
    featured: false,
    description: "Creative platform celebrating independent artists and creators",
    img: "/projects/indie-island/banner.jpg",
    url: "#",
    longDescription:
      "Indie Island is a fictional music festival developed through a shared conceptual process, after which each participant created their own interpretation. This is my visual outcome in the form of festival posters. The festival targets the 20–35 age group and is based on key concepts such as warmth, the indie scene, and a sense of community. Created mainly in Adobe Photoshop, with elements from Illustrator. The posters were produced in multiple formats to practice composition and adaptation of graphic elements.",
    gallery: [
      "/projects/indie-island/ig-fb-portrait-1080x1350.jpg",
      "/projects/indie-island/ig-post.jpg",
      "/projects/indie-island/banner.jpg",
      "/projects/indie-island/smartphone-mockup.jpg",
      "/projects/indie-island/large-banner-mockup.jpg",
      "/projects/indie-island/poster-mockup.jpg",
      "/projects/indie-island/ig-story-1080x1920.jpg",
      "/projects/indie-island/story-4.jpg",
    ],
    videos: null,
  },
  {
    id: "bonan-och-boken",
    name: "Bönan & Boken",
    featured: false,
    description: "Cozy café and bookshop experience with warm, inviting design",
    img: "/projects/bonan-och-boken/bonan-boken-profile-1.png",
    url: "#",
    longDescription:
      "A project where I was given full creative freedom to develop a graphic identity for a fictional café. The work included logo design and an overall visual expression, with a focus on creating a warm and cohesive identity. Created in Adobe Illustrator.",
    gallery: ["/projects/bonan-och-boken/bonan-boken-profile-1.png", "/projects/bonan-och-boken/bonan-boken-profile-2.png"],
    videos: null,
  },
];

export const FEATURED_PROJECTS = PORTFOLIO_CONTENT.filter((p) => p.featured);
